# Generated by Django 3.2 on 2021-05-04 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название жанра')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'db_table': 'genres',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2, verbose_name='название уровня английского')),
            ],
            options={
                'verbose_name': 'уровень английского',
                'verbose_name_plural': 'уровни английского',
                'db_table': 'levels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название режима')),
            ],
            options={
                'verbose_name': 'режим тренировки',
                'verbose_name_plural': 'режимы тренировки',
                'db_table': 'modes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('is_adult_content', models.BooleanField(default=True, verbose_name='просмотр контента для несовершеннолетних')),
                ('is_signup', models.BooleanField(default=False, verbose_name='подписка на новости')),
                ('perfect', models.TextField(blank=True, verbose_name='упражнения идеальные')),
                ('mistakes', models.TextField(blank=True, verbose_name='упражнения с ошибками')),
                ('points', models.IntegerField(default=0, verbose_name='опыт')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('genres', models.ManyToManyField(to='loginsys.Genres', verbose_name='жанр')),
                ('levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginsys.levels', verbose_name='уровень английского')),
                ('modes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginsys.modes', verbose_name='режим тренировки')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'all_users',
                'ordering': ['-data_joined', 'id'],
            },
        ),
    ]
