# Generated by Django 3.2 on 2021-05-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_alter_profiles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='levels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginsys.levels', verbose_name='уровень английского'),
        ),
    ]
