# Generated by Django 3.2 on 2021-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_alter_profiles_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='levels',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='modes',
            new_name='mode',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='genres',
            field=models.ManyToManyField(to='loginsys.Genres', verbose_name='жанры'),
        ),
    ]
