# Generated by Django 3.2 on 2021-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20210506_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='was_online',
            field=models.DateTimeField(default='2021-01-01 00:00', verbose_name='последняя активность'),
        ),
    ]
