# Generated by Django 3.2 on 2021-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0005_profiles_was_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='was_online',
            field=models.DateTimeField(default='2021-01-01 00:00', verbose_name='последняя активность'),
        ),
    ]
