# Generated by Django 3.2 on 2021-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginsys', '0004_auto_20210506_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('artist', models.CharField(max_length=150, verbose_name='исполнитель')),
                ('difficulty', models.IntegerField(verbose_name='сложность')),
                ('limit', models.BooleanField(verbose_name='контент, содержащий нецензурную лексику')),
                ('link', models.CharField(blank=True, max_length=150, verbose_name='ссылка')),
                ('lyrics', models.TextField(verbose_name='текст')),
                ('genre', models.ManyToManyField(to='loginsys.Genres', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'песни',
                'db_table': 'all_songs',
                'ordering': ['id', 'title'],
            },
        ),
    ]
