# Generated by Django 3.2 on 2021-05-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='songs',
            table='songs',
        ),
    ]
