# Generated by Django 3.2 on 2021-05-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20210506_1548'),
        ('songs', '0003_alter_songs_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='genre',
        ),
        migrations.AddField(
            model_name='songs',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loginsys.genres', verbose_name='жанр'),
        ),
    ]
